### PR TITLE
Backpropagation

### PR DESCRIPTION
**Pull request by dcferreira**
Some corrections on chapter 6.4.1.
Please double-check, in particular equations 6.31, 6.32 and 6.34, but I believe my changes are correct.

### CODE REVIEW

**Comment by ramon-astudillo** [comment]
Merged most of the changes. The n -> N in formulas was incorrect.

**Comment by dcferreira** [comment]
In equation 6.17 in particular, n isn't defined.
What I understood was that the gradient of layer n only depends on the layers after n (that is, from n to N), so the layer n-1 shouldn't be there.

Did I get this wrong?

**Comment by ramon-astudillo** [comment]
Regarding Eq 6.17 and the definition of n/N, you are right I will make it more clear and take your n-1 -> N-1 suggestion.

Regarding the gradient question, are you referring to the typo you found in Eq. 6.32?. I had included that one.

**Comment by dcferreira** [comment]
My post was only about the n-1 -> N-1 subject. I think your commit is correct :)

**Pull request closed without merging**
